### ISSUE TITLE
Plugin doesn't index old items

### ISSUE THREAD

**Issue by CIRDOC** [Harvard-ATG/omeka-plugin-Elasticsearch#4]
Hi,

Still trying to use your still excellent plugin but I've some kind of strange thing happening..
The plugin doesn't index my old items until I do edit and save them.
The problem is that I already have over 8000 items and that I can't do the trick for all of them :(
Any brilliant idea for solving that ?

Thanks !

**Comment by arthurian** [comment]
Hi @CIRDOC, the plugin doesn't automatically index old items when it is first installed. The solution is to force the plugin to reindex everything, including old items.

Try this:

1. Login to the admin interface of your site.
2. Go to _Elasticsearch > Index_ 
3. Click the **Clear and Reindex** button. This should trigger a background job that reindexes all of your old items. When that is done, items should be indexed automatically when they are updated, deleted, or created.

**Comment by CIRDOC** [comment]
Hi,
Tried that several times but only the trick of re-edit and re-save the item did the job..
Thanks for taking time with my issues !

**Comment by arthurian** [comment]
@CIRDOC What version of Omeka are you running? Also, when you do the reindexing, is the job status displayed as _completed_? Usually when there's an error in the job, the status is either _error_ or _in progress_ (if the process did not exit cleanly).

If the job status is _completed_ successfully, then you might check your application log file, `application/logs/error.log`, to see how many items it is attempting to index. You should see something similar to this in your log file when you initiate the reindexing:

```
2017-12-22T15:28:34+00:00 INFO (6): Elasticsearch: indexAll items: 260
2017-12-22T15:28:34+00:00 INFO (6): Starting bulk indexing at 1513956514.3656
2017-12-22T15:28:34+00:00 INFO (6): Bulk indexing 260 documents in batches of 500 with timeout 90
```

If you could show a sample like that, it might help to figure out the issue.

**Comment by CIRDOC** [comment]
@arthurian 
Omeka v2.6 / php v7.0.10 / mysql v5.7.14 / WAMP / windows 10
The jobs status stands on starting and never change
The errors.log file is totally empty...
Tell me what more I can do to help ?

**Comment by arthurian** [comment]
@CIRDOC Do you see anything in your apache error log that might be related (e.g. some sort of PHP runtime error)?

**Comment by CIRDOC** [comment]
@arthurian 
Nope, nothing anywhere. Searched in php and apache error logs.
Could'nt it be an issue due to windows system ?
Sorry, I feel useless and taking your time for nothing !

**Comment by CIRDOC** [comment]
@arthurian  Hey ! I installed a new omeka on linux and retried, everything worked fine.
Everybody is getting indexed ! So I guess the issue is due to Windows OS...
