### ISSUE TITLE
Problem with multi-input field

### ISSUE THREAD

**Issue by CIRDOC** [Harvard-ATG/omeka-plugin-Elasticsearch#6]
Dear @arthurian,

Seems like multi inputs field are not properly imported in elastic. 
I just keep on getting the last entered data for a 3 input title for example.
Any idea about what I'm making wrong ?

Thanks !

**Comment by CIRDOC** [comment]
Searched a bit and :
in the elements field I do get two fileds with same displayName and Name (like for Language)
but
in the element just one of each...
Adding an extract down here :
`            {
                "_index": "omeka2",
                "_type": "doc",
                "_id": "item_3925",
                "_score": 5.6590466,
                "_source": {
                    "resulttype": "Item",
                    "model": "Item",
                    "modelid": 3925,
                    "featured": false,
                    "public": false,
                    "created": "2014-03-26T08:08:47+00:00",
                    "updated": "2017-03-29T15:44:54+00:00",
                    "title": "Mistral 1830-1930. Nice / Bandieri ",
                    "collection": "Ressources du Languedoc-Roussillon sur Occitanica",
                    "itemtype": "Image fixe",
                    "elements": [
                        {
                            "displayName": "Title",
                            "name": "title"
                        },
                        {
                            "displayName": "Alternative Title",
                            "name": "alternativetitle"
                        },
                        {
                            "displayName": "Subject",
                            "name": "subject"
                        },
                        {
                            "displayName": "Description",
                            "name": "description"
                        },
                        {
                            "displayName": "Creator",
                            "name": "creator"
                        },
                        {
                            "displayName": "Source",
                            "name": "source"
                        },
                        {
                            "displayName": "Publisher",
                            "name": "publisher"
                        },
                        {
                            "displayName": "Date",
                            "name": "date"
                        },
                        {
                            "displayName": "Rights",
                            "name": "rights"
                        },
                        {
                            "displayName": "Abstract",
                            "name": "abstract"
                        },
                        {
                            "displayName": "Relation",
                            "name": "relation"
                        },
                        {
                            "displayName": "Format",
                            "name": "format"
                        },
                        {
                            "displayName": "Format",
                            "name": "format"
                        },
                        {
                            "displayName": "Language",
                            "name": "language"
                        },
                        {
                            "displayName": "Language",
                            "name": "language"
                        },
                        {
                            "displayName": "Type",
                            "name": "type"
                        },
                        {
                            "displayName": "Type",
                            "name": "type"
                        },
                        {
                            "displayName": "Identifier",
                            "name": "identifier"
                        },
                        {
                            "displayName": "Temporal Coverage",
                            "name": "temporalcoverage"
                        },
                        {
                            "displayName": "Région Administrative",
                            "name": "rgionadministrative"
                        },
                        {
                            "displayName": "Variante Idiomatique",
                            "name": "varianteidiomatique"
                        }
                    ],
                    "element": {
                        "title": "Mistral 1830-1930. Nice / Bandieri ",
                        "alternativetitle": "Frédéric Mistral  portrait sculpté par L. Maubert / Bandieri Photogr. [document iconographique]",
                        "subject": "Mistral, Frédéric (1830-1914)",
                        "description": "Carte postale. Frédéric Mistral  portrait sculpté par L. Maubert [document iconographique]",
                        "creator": "Photogr. Bandieri",
                        "source": "CIRDÒC - Mediatèca occitana, IC-A-1.MIS-2-24",
                        "publisher": "Société Générale d'Imprimerie. Nice",
                        "date": "1930",
                        "rights": "Certains droits réservés contacter le CIRDOC",
                        "abstract": "Textes accompagnement Mistral et  Dévoluy",
                        "relation": "Vignette : \r\nhttp://occitanica.org/omeka/files/original/404c2cea7649045e2ed7567e0e414e07.jpg",
                        "format": "13,8 x 9 cm",
                        "language": "pro",
                        "type": "image fixe",
                        "identifier": "http://occitanica.org/omeka/items/show/3925",
                        "temporalcoverage": "19..",
                        "rgionadministrative": "Languedoc-Roussillon",
                        "varianteidiomatique": "Provençal"
                    },
                    "tags": [
                        "Bandieri",
                        "Carta postala",
                        "Carte postale",
                        "Frederi Mistral",
                        "Frédéric Mistral",
                        "L. Maubert",
                        "Nice",
                        "Pèire Devoluy",
                        "Pierre Devoluy"
                    ],
                    "files": [
                        {
                            "id": 2370,
                            "title": "IC-A-1.MIS-2-24.jpg",
                            "element": []
                        }
                    ]
                }`

**Comment by arthurian** [comment]
Hi @CIRDOC,

Can you give a little more information about how you're using the plugin in your site? How do you have your elements setup? Can you show a screenshot of what you mean by a multi-input title? Also, what would you expect the index to return for your title element?

Without knowing those details, it sounds like you possibly have multiple elements with the same label (e.g. Title, or Format), but the elasticsearch plugin assumes that you only ever have one element labeled "Title" or "Format". This causes the last "Title" or "Format" element to be used in the results. 

We're looking into a configuration interface that would allow you to specify exactly which elements you want to index, so that you can avoid indexing multiple elements with the same name. But any additional information or context you can provide would be helpful.

**Comment by CIRDOC** [comment]
Dear @arthurian,

I'll try to explain the problem with my poor english... I hope it will make the job !
The plugin is used as, I believe, it was made to :
 Installed and running fine without any trouble.
Here are two screenshots of an object with multiple inputed values (in this case it is multiple subjects) and the result I get with Elastic : 

![img1](https://user-images.githubusercontent.com/25080167/38601630-8ed085c2-3d68-11e8-9d3f-e65e91390fdd.jpg)
![img2](https://user-images.githubusercontent.com/25080167/38601638-92133a90-3d68-11e8-819a-2b060239b12e.jpg)

As you say, the plugin just stores one value for this subject field as there are actually 4.

I checked the Solr module (https://github.com/scholarslab/SolrSearch -> https://github.com/scholarslab/SolrSearch/blob/master/solr-core/omeka/conf/schema.xml) and they are using some multivalued attribute in the schema... Don't know if this can help and even if elastic can handle that...

![img3](https://user-images.githubusercontent.com/25080167/38601873-55864f80-3d69-11e8-9f4a-5be4cf97f923.jpg)

Hope I was a bit helpful on this issue :)

Thanks one more time for responding to questions !!

**Comment by arthurian** [comment]
Hi @CIRDOC, yes that's super helpful! The problem is clear now -- we need to be able to index and display multi-valued inputs. 

I've created PR https://github.com/Harvard-ATG/omeka-plugin-Elasticsearch/pull/7 which should hopefully resolve the issue (with screenshots). Note that this will require re-indexing the site. Let me know if that looks like it will resolve the problem.

**Comment by CIRDOC** [comment]
@arthurian , tested and validated! 
It looks like it works perfectly !
Thanks !

**Comment by arthurian** [comment]
@CIRDOC Thanks for testing and validating. I merged the PR and created a new release with the updates.
